# Generated by Django 6.1.1 on 2026-09-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default="Jasurbek Jo'rayev", max_length=120)),
                ('role_title', models.CharField(default='Python Backend Developer', max_length=150)),
                ('tagline', models.CharField(blank=True, help_text='Short one-line hook shown under your name in the hero section.', max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, default='Uzbekistan', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telegram_username', models.CharField(blank=True, help_text='Without the @ sign, e.g. JORAYEV_0709', max_length=50)),
                ('github_url', models.URLField(blank=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('education_place', models.CharField(blank=True, default="Najot Ta'lim", max_length=120)),
                ('education_program', models.CharField(blank=True, max_length=150)),
                ('education_period', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='Used as the <meta name=description> for the homepage.', max_length=160)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('LANG', 'Languages'), ('BACKEND', 'Backend'), ('FRONTEND', 'Frontend'), ('DATA', 'Databases & Data'), ('AI', 'AI & APIs'), ('TOOLS', 'Tools & DevOps')], max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
